version: '3.4'

services:
  template.webapi:
    image: ${DOCKER_REGISTRY-}templatewebapi
    build:
      context: .
      dockerfile: src/Template.WebApi/Dockerfile
#    depends_on:
#            - mongo
#
#  mongo:
#    image: mongo
#    restart: always
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: root
#      MONGO_INITDB_ROOT_PASSWORD: example
#    ports:
#      - "27017:27017"
